# Configuração do servidor Eureka 
eureka:
  instance:
    hostname: localhost
  client:  # Não se registrar como cliente
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 1111   # Porta de conexão
