spring:
  application:
    name: aluno-service  

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://54.211.117.202/:1111/eureka/

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port
